
= Clojure Demo of Exuberant Ctags and ZPrint 

Improve your Clojure editing experience with Vim or Emacs.

== Overview

If you can't use a full IDE like Cursive (IntelliJ/IDEA) for Clojure development, 
you can still make progress using a more traditional editor like Vim or Emacs.
Two tools that make a big improvement are:

- http://ctags.sourceforge.net/[Exuberant Ctags]

- https://github.com/kkinnear/zprint[Clojure ZPrint]

== Exuberant Ctags

As described
https://en.wikipedia.org/wiki/Ctags[by Wikipedia]
`ctags` is a tool which will scan your source code files and index identifiers 
like function names and top-level variables. 

=== Verify homebrew is installed (download from https://brew.sh[brew.sh] if necessary)

```bash
> brew --version
Homebrew 3.1.1
```

=== Install Ctags on a Mac

Look up info on ctags

```bash
> brew info ctags
ctags: stable 5.8 (bottled), HEAD
Reimplementation of ctags(1)
https://ctags.sourceforge.io/
/usr/local/Cellar/ctags/5.8_2 (9 files, 360.2KB) *
  Poured from bottle on 2021-04-13 at 17:05:02
...
```

Install ctags

```bash
> brew install ctags
```

Install Vim if necessary

```bash
> brew install macvim    # Notice the spelling!
```

Run the `ctags` program, which creates an output file `./tags`

```
ctags -R .      # recursive run starting at current dir
```

I like to set up the Vim search path for the tags file as:

```
set tags=./tags,../tags,../../tags,../../../tags,../../../../tags,tags
```
in my `~/.vimrc` file. Type `:help tag-commands` to see full Vim documentation.

Now edit a file: 

```
gvim test/clj/tst/demo/core.clj   # or just `vim` for non-GUI version
```

Go the the end of the file, and put your cursor on the `walk-impl` symbol. Hit
CTRL-<right-square-bracket> (i.e. `^]`), and Vim will jump to the definition of the `walk-impl`
function. Move down a few lines to where `walk-map` is called.  Put the cursor on the the function
name and repeat `^]`, and Vim jumps to the definition of that function.  

Each "tag" command moves the cursor, saving the starting location on a stack.  To retrace your
steps, type CTLR-t (i.e. `^t`). Each time Vim will move the cursor back to the site of the previous
location, until the stack is exhausted.

=== Using Ctags with Emacs

Emacs also understands `ctags`, but uses a different file format.  Invoke the program as:

```
ctags -e -R .
```

to generate an Emacs-format `tags` file.

=== Using Ctags with Other Editors

Wikipedia lists 
https://en.wikipedia.org/wiki/Ctags#Editors_that_support_ctags[many other editors]
as being able to use Ctags, including Atom and VS Code.




== Formatting Clojure Source Code with ZPrint

=== Installing ZPrint

The simplest way to install ZPrint is to download a pre-build uberjar of ZPrint 
https://github.com/kkinnear/zprint/releases/download/1.1.1/zprint-filter-1.1.1[such as this one].

Verify the file downloaded and is a JAR file:

```
> file ~/Downloads/zprint-filter-1.1.1
/Users/alanthompson/Downloads/zprint-filter-1.1.1: Java archive data (JAR)
```

I place it in a convenient location in my home directory and add in the missing `.jar` suffix

```
> mkdir ~/opt
> mv ~/Downloads/zprint-filter-1.1.1 ~/opt/zprint.jar
```

To make running ZPrint fast & simple, add an alias to your `~/.zshrc` file:

```
alias zpru="java  -jar ~/opt/zprint.jar  -w **/*.clj* "   # uses ZSH wildcards to find all `*.clj` files
```

If you are using BASH, you will need to use `find` or similar to walk the directory tree 

```
alias zpru="java  -jar ~/opt/zprint.jar  -w  $(find . -name '*.clj{,c,s}') "   

```

You also need to create a configuration file `~/.zprintrc`.  After much experimentation, I recommend
using the following configuration for Clojure source code:

```
> cat ~/.zprintrc
{:width    125
 :style    :respect-nl 
 :map      {:justify? true}
 :binding  {:justify? true}
 :pair     {:justify? true}
}
```

Make sure you have Java installed:

```bash
> java --version
java 13 2019-09-17
Java(TM) SE Runtime Environment (build 13+33)
Java HotSpot(TM) 64-Bit Server VM (build 13+33, mixed mode, sharing)
```

and the you can run ZPrint:

```
> zpru     # invoke the uberjar using the alias
```

It only takes a second or two to reformat all the matching `\*.clj`, `*.cljc`, and `*.cljs` files.
If edit a source file, you can experiment with moving around the source code, then running
`ZPrint` and reloading the file to see how `ZPrint` reformats the code (note, ZPrint will never
delete a blank line) with the above configuration.








== License

Copyright © 2021  Alan Thompson

Distributed under the link:https://www.eclipse.org/legal/epl-v10.html[Eclipse Public License], the same as Clojure.

